### ISSUE TITLE
House Owed Stats?

### ISSUE THREAD

**Issue by Urliq** [Ormannishe/WoWGoldGambler#2]
Would it be possible to get the gold owed to the house by each character for the current session? Having trouble keeping track since people generally don't deposit gold until a break or end of the raid.

**Comment by Ormannishe** [comment]
Good idea - I'll look into it.

**Comment by Ormannishe** [comment]
@Urliq Thanks for the suggestion! I've merged the change and will release a new version of the addon on CurseForge shortly!
