### ISSUE TITLE
Game Mode Idea: Lottery

### ISSUE THREAD

**Issue by jrooc** [Ormannishe/WoWGoldGambler#8]
The wager amount is the lottery winnings.

All players /roll 999999 to get their lottery ticket. WoWGoldGambler then simply draws one of the numbers to determine the winner.

Winner: The player who's lottery ticket was drawn.

Loser: ALL players who's lottery ticket was not drawn

Payment Amount: The wager amount divided equally among all losers (rounding when necessary).

**Comment by jrooc** [comment]
This might be an improved version of Roulette, since there will always be a winner.

**Comment by Ormannishe** [comment]
A version of this was implemented in [this PR](https://github.com/Ormannishe/WoWGoldGambler/pull/10), replacing Roulette. Instead of the idea above, players simply register and their 'lotto number' is their player index.
